package aerosur;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Timestamp;


import java.util.List;


/**
 *
 * @author Anderson
 */
public class frmVuelos extends javax.swing.JFrame {

    /**
     * Creates new form frmVuelos
     */
    public frmVuelos() {
        initComponents();
      
    }
    private void buscarVuelo(String numeroVuelo) {
    VueloDAO vueloDAO = new VueloDAO();
    Vuelo vuelo = vueloDAO.buscarVueloPorNumero(numeroVuelo);

    if (vuelo != null) {
        // Llenar los campos del vuelo
        txtnovuelobuscar.setText(vuelo.getNumeroVuelo());
        txtaereabuscar.setText(vuelo.getLineaAerea());
        txtorigenbuscar.setText(vuelo.getOrigen());
        txtdestinobuscar.setText(vuelo.getDestino());
        txtsalidabuscar.setText(vuelo.getFechaSalida().toString());
        txtentradabuscar.setText(vuelo.getFechaIngreso().toString());

        // Configurar el modelo de la tabla de tripulación
        DefaultTableModel modelTripulacion = new DefaultTableModel(new String[]{"Pasaporte", "Nombre", "Nacionalidad", "Puesto"}, 0);
        for (Tripulante tripulante : vuelo.getTripulacion()) {
            modelTripulacion.addRow(new Object[]{tripulante.getPasaporte(), tripulante.getNombre(),
                tripulante.getNacionalidad(), tripulante.getPuesto()});
        }
        tbltripulacionbuscar.setModel(modelTripulacion);

        // Configurar el modelo de la tabla de pasajeros
        DefaultTableModel modelPasajeros = new DefaultTableModel(new String[]{"Nombre", "Apellido", "Nacionalidad", "Asiento", "Pasaporte"}, 0);
        for (Pasajero pasajero : vuelo.getPasajeros()) {
            modelPasajeros.addRow(new Object[]{pasajero.getNombre(), pasajero.getApellido(),
                pasajero.getNacionalidad(), pasajero.getAsiento(), pasajero.getPasaporte()});
        }
        tblpasajerosbuscar.setModel(modelPasajeros);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Vuelo no encontrado.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtorigenbuscar = new javax.swing.JTextField();
        txtsalidabuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtdestinobuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtnovuelobuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtentradabuscar = new javax.swing.JTextField();
        txtaereabuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpasajerosbuscar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltripulacionbuscar = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtorigenbuscar.setEditable(false);
        txtorigenbuscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        txtorigenbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorigenbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtorigenbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 185, -1));

        txtsalidabuscar.setEditable(false);
        txtsalidabuscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        getContentPane().add(txtsalidabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 185, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha de Salida");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jPanel1.setBackground(new java.awt.Color(29, 73, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdestinobuscar.setEditable(false);
        txtdestinobuscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        txtdestinobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdestinobuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtdestinobuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 185, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destino");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 73, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VER VUELOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 60));

        txtnovuelobuscar.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jPanel1.add(txtnovuelobuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 130, 30));

        btnbuscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ver-archivo-70.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setBorderPainted(false);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setFocusCycleRoot(true);
        btnbuscar.setFocusPainted(false);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ver-archivo-80.png"))); // NOI18N
        btnbuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ver-archivo-70.png"))); // NOI18N
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 90, 130));

        btnRegresar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-flecha-izquierda-80.png"))); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setDefaultCapable(false);
        btnRegresar.setFocusPainted(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-flecha-izquierda-90.png"))); // NOI18N
        btnRegresar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-flecha-izquierda-80.png"))); // NOI18N
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 100));

        txtentradabuscar.setEditable(false);
        txtentradabuscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jPanel1.add(txtentradabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 185, -1));

        txtaereabuscar.setEditable(false);
        txtaereabuscar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        txtaereabuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaereabuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtaereabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 185, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Ingreso");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Orígen");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 56, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Vuelo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Línea Aérea");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        tblpasajerosbuscar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tblpasajerosbuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpasajerosbuscar.setEnabled(false);
        jScrollPane1.setViewportView(tblpasajerosbuscar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 756, 126));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PASAJEROS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        tbltripulacionbuscar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tbltripulacionbuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltripulacionbuscar.setEnabled(false);
        jScrollPane2.setViewportView(tbltripulacionbuscar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 759, 116));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TRIPULACIÓN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 145, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtorigenbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorigenbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorigenbuscarActionPerformed

    private void txtdestinobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdestinobuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdestinobuscarActionPerformed

    private void txtaereabuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaereabuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaereabuscarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String numeroVuelo = txtnovuelobuscar.getText();
        buscarVuelo(numeroVuelo);

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Crear una instancia del formulario
        FormPrincipal form = new FormPrincipal();
        
        // Hacer visible el formulario
        form.setVisible(true);
        
        // Centrar el formulario en la pantalla
        form.setLocationRelativeTo(null);
    
        form.setVisible(true);  // Hace visible el formulario
        
        // Cerrar el formulario actual (FormPrincipal)
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblpasajerosbuscar;
    private javax.swing.JTable tbltripulacionbuscar;
    private javax.swing.JTextField txtaereabuscar;
    private javax.swing.JTextField txtdestinobuscar;
    private javax.swing.JTextField txtentradabuscar;
    private javax.swing.JTextField txtnovuelobuscar;
    private javax.swing.JTextField txtorigenbuscar;
    private javax.swing.JTextField txtsalidabuscar;
    // End of variables declaration//GEN-END:variables
}
